### ISSUE TITLE
Save Transports filters more presistent in browser

### ISSUE THREAD

**Issue by neumantm** [c3loc/transporte#17]
Should survive reload

**Comment by psy** [comment]
the datatables plugin should already do that.

**Comment by neumantm** [comment]
Only the `hide done` is a problem for me.
I'm using firefox 70.0.1 (64-bit) on NixOS 19.09.
Looks like [transport_list.html#L116](https://github.com/c3loc/transporte/blob/master/transporte/templates/transport_list.html#L116) correctly clicks on the checkbox, which causes [L102](https://github.com/c3loc/transporte/blob/master/transporte/templates/transport_list.html#L102) to run and then [L103](https://github.com/c3loc/transporte/blob/master/transporte/templates/transport_list.html#L103) overwrites the local storage item `hideDone` with `false`

**Comment by neumantm** [comment]
Fixed by #20
